### ISSUE TITLE
ImportError: cannot import name superlu

### ISSUE THREAD

**Issue by techolga** [williamhunter/ToPy#39]
When I try `python scripts/optimise.py examples/heat/heat_3d_etaopt_gsf_dquad.tdp` I get this error:
```
Traceback (most recent call last):
  File "scripts/optimise.py", line 8, in <module>
    import topy
  File "/usr/local/lib/python2.7/dist-packages/topy/__init__.py", line 8, in <module>
    from .topology import *
  File "/usr/local/lib/python2.7/dist-packages/topy/topology.py", line 14, in <module>
    from pysparse import superlu, itsolvers, precon
ImportError: cannot import name superlu
```
I think it is cause i was not able to install pysparse, when i try `sudo pip install pysparse`i receive this error:
```
compile options: '-DLENFUNC_OK=1 -DSCIPY_MKL_H -DHAVE_CBLAS -Ipysparse/sparse/src -I/tmp/pip-install-UotukF/pysparse/pysparse/include -I/usr/local/include -I/usr/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/tmp/pip-install-UotukF/pysparse/pysparse/include -I/usr/include/python2.7 -c'
    x86_64-linux-gnu-gcc: pysparse/sparse/src/spmatrixmodule.c
    pysparse/sparse/src/spmatrixmodule.c:4:22: fatal error: spmatrix.h: No such file or directory
    compilation terminated.
    pysparse/sparse/src/spmatrixmodule.c:4:22: fatal error: spmatrix.h: No such file or directory
    compilation terminated.
    error: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DLENFUNC_OK=1 -DSCIPY_MKL_H -DHAVE_CBLAS -Ipysparse/sparse/src -I/tmp/pip-install-UotukF/pysparse/pysparse/include -I/usr/local/include -I/usr/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/tmp/pip-install-UotukF/pysparse/pysparse/include -I/usr/include/python2.7 -c pysparse/sparse/src/spmatrixmodule.c -o build/temp.linux-x86_64-2.7/pysparse/sparse/src/spmatrixmodule.o -MMD -MF build/temp.linux-x86_64-2.7/pysparse/sparse/src/spmatrixmodule.o.d" failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-UotukF/pysparse/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-BwLxfU/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-UotukF/pysparse/
```
any suggestions? I already tried to build Atlas cause `sudo apt-get install Atlas3-base-def` gave me "Unable to locate package" but it  still gave me the same error.

**Comment by williamhunter** [comment]
You need to install all the sources required for PySparse of you want to
build from sources.

sudo apt-get source <package>

**Comment by techolga** [comment]
I tried `sudo apt-get source pysparse python-numpy python-matplotlib python-pyvtk` then `sudo python setup.py build` getting the same error as before when trying to build pysparse:
```
compile options: '-DUSE_VENDOR_BLAS=1 -DSCIPY_MKL_H -DHAVE_CBLAS -Ipysparse/direct/src -Ipysparse/direct/superlu/include -I/usr/local/include -I/usr/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/home/jayohh/topy/pysparse/pysparse/include -I/usr/include/python2.7 -c'
x86_64-linux-gnu-gcc: pysparse/direct/superlu/src/util.c
In file included from pysparse/direct/superlu/src/util.c:23:0:
pysparse/direct/superlu/include/util.h:94:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 extern void    StatFree();
 ^
pysparse/direct/superlu/include/util.h:100:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 extern double  SuperLU_timer_ ();
 ^
pysparse/direct/superlu/src/util.c: In function ‘superlu_abort_and_exit’:
pysparse/direct/superlu/src/util.c:32:5: error: format not a string literal and no format arguments [-Werror=format-security]
     fprintf(stderr, msg);
     ^
pysparse/direct/superlu/src/util.c: At top level:
pysparse/direct/superlu/src/util.c:251:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 StatFree()
 ^
pysparse/direct/superlu/src/util.c:260:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 LUFactFlops()
 ^
pysparse/direct/superlu/src/util.c:266:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 LUSolveFlops()
 ^
cc1: some warnings being treated as errors
In file included from pysparse/direct/superlu/src/util.c:23:0:
pysparse/direct/superlu/include/util.h:94:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 extern void    StatFree();
 ^
pysparse/direct/superlu/include/util.h:100:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 extern double  SuperLU_timer_ ();
 ^
pysparse/direct/superlu/src/util.c: In function ‘superlu_abort_and_exit’:
pysparse/direct/superlu/src/util.c:32:5: error: format not a string literal and no format arguments [-Werror=format-security]
     fprintf(stderr, msg);
     ^
pysparse/direct/superlu/src/util.c: At top level:
pysparse/direct/superlu/src/util.c:251:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 StatFree()
 ^
pysparse/direct/superlu/src/util.c:260:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 LUFactFlops()
 ^
pysparse/direct/superlu/src/util.c:266:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 LUSolveFlops()
 ^
cc1: some warnings being treated as errors
error: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE_VENDOR_BLAS=1 -DSCIPY_MKL_H -DHAVE_CBLAS -Ipysparse/direct/src -Ipysparse/direct/superlu/include -I/usr/local/include -I/usr/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/home/jayohh/topy/pysparse/pysparse/include -I/usr/include/python2.7 -c pysparse/direct/superlu/src/util.c -o build/temp.linux-x86_64-2.7/pysparse/direct/superlu/src/util.o -MMD -MF build/temp.linux-x86_64-2.7/pysparse/direct/superlu/src/util.o.d" failed with exit status 1
```
looks like superlu is missing but `sudo apt-get install libsuperlu-dev` doesnt do the trick. 
I think its a problem with linking the needed packages with setup.py or setup.cfg...

**Comment by williamhunter** [comment]
Sources for Atlas installed?

If you head over to the doc section on GitHub, have a look at my thesis, I
think I give details of how to build from source. But it's almost been 10
years, so it may be a little outdated.

**Comment by techolga** [comment]
Yea got Atlas sources too, already read your doc, the problem is that `Atlas3-base-dev` is not found and I am not sure if the new atlas package `libatlas-base-dev` is compatible with pysparse. I think it has to be a package failure, because it is the same error when i use a wrong lib path as when i use the right one, it tries to compile and then stops at the first file.

**Comment by techolga** [comment]
Used Simon Fojtus Python3 Fork that works without pysparse.
