### ISSUE TITLE
Can't install totally the program : "cannot import name superlu"

### ISSUE THREAD

**Issue by MsURGZI** [williamhunter/ToPy#9]
Hello,

I just installed pip, matplotlib, simpy, numpy, python-dev, pysparse (and of course topy) and now, **it tells me that superlu isn't there.**

I'm pretty much new about programming, so it's probably a mistake from a non-used to script person. I'm just starting to make few steps here.

I run Ubuntu 15.10 on a 64 bits machine, I use the system python language (Python 2.7.10).

**Command typed**

`$ python optimise.py beam_2d_reci.tpd`                      

**Results**

```
Traceback (most recent call last):                                    
  File "optimise.py", line 16, in <module>
    import topy
  File "/usr/local/lib/python2.7/dist-packages/topy/__init__.py", line 8, in <module>
    from topology import *
  File "/usr/local/lib/python2.7/dist-packages/topy/topology.py", line 19, in <module>
    from pysparse import superlu, itsolvers, precon
ImportError: cannot import name superlu
```

**Comment by williamhunter** [comment]
Did you install superlu before you built pysparse?

Regards,
William Hunter

**Comment by MsURGZI** [comment]
**Thanks for the answer !**

I just installed PySparse, I didn't know about superlu.
It seems that PySparse doesn't install, I don't know why.
I installed NumPy, as it's writed everywhere I need it to install PySparse.
The readme from PySparse tells "PySparse is needs to link against the BLAS and LAPACK libraries,
   which must be available on your system.", so I installed both of them successfully. 

But I get a lot of mistake while installing PySparse, and a lot of things are missing after installed. So the error is during the installation of PySparse.

I run python.py after downloaded, as explained [here](http://pysparse.sourceforge.net/introduction.html#installing-pysparse), but the example (from PySparse) is completely crashed when I try to run it.

```
Traceback (most recent call last):
  File "test/testSuperlu.py", line 3, in <module>
    from pysparse.tools import poisson
ImportError: No module named tools
```

**Comment by williamhunter** [comment]
Pysparse can be a pain to install...

Try installing via pip, but read this first:
http://stackoverflow.com/questions/25459011/how-to-build-pysparse-on-ubuntu#25460414

Any luck?

**Comment by MsURGZI** [comment]
I did kind of abandon this thing (I'm not on this everyday), however, I did reinstall it on another Linux. It's Mint (xfce) 18, based on ubuntu 16.04, and it worked fine using the following commands on a terminal : 

```
sudo apt-get install -y git python-dev libpython-dev libevent-dev libsuperlu-dev 
libblas-dev liblapack-dev

git clone https://github.com/williamhunter/topy

apt install python-pip
pip install --upgrade pip
pip install matplotlib


sudo pip install setuptools
sudo pip install SymPy
sudo pip install csc-pysparse
```

(note that I did run the one you did advise, but any other won't work, because of a "fatal error: 'spmatrix.h' file not found". I tried `sudo pip install pysparse`, `sudo pip install pysparse==1.2-dev213`, `sudo pip install --pre pysparse`, `sudo pip install -e git+http://git.code.sf.net/p/pysparse/git#egg=PySparse`... However, the `csc-pysparse` seemed to work)

Then I moved to the topy folder, to execute setup.py : 
`sudo python setup.py install`, where it seems to run perfectly.

As advised in the tutorial, I copied the `optimise.py` (from `script` folder) where my tpd file is (`topy/examples/mbb_beam`). I try to run topy, like this: `python optimise.py bea_2d_reci.tpd`

But it crashed, with a message telling me that there is some problem, apparently with superlu, which should have been installed with the pip install pysparse:

```
Traceback (most recent call last):
  File "optimise.py", line 13, in <module>
    import topy
  File "/usr/local/lib/python2.7/dist-packages/topy/__init__.py", line 8, in <module>
    from topology import *
  File "/usr/local/lib/python2.7/dist-packages/topy/topology.py", line 19, in <module>
    from pysparse import superlu, itsolvers, precon
ImportError: cannot import name superlu
```

Sorry to only get back on this this late, hope you didn't take it bad.

**Comment by MsURGZI** [comment]
> Did you install superlu before you built pysparse? Regards, William Hunter

I tried, I may be wrong, but `sudo apt-get install libsuperlu-dev` should do the trick, right ? Why it keeps telling me "cannot import name superlu" ?

**Comment by williamhunter** [comment]
I haven't worked on a Linux machine in a few years so I'm a bit rusty. If
you want to pull in all the dependencies to build from source, you can
issue the following on a Debian based distribution, for example for NumPy:

sudo apt-get build-dep python-numpy

For Pysparse:

sudo apt-get install atlas3-base-dev

However, make sure to read the install files that come with Pysparse, it
may have changed since I last built Pysparse from source.

**Comment by williamhunter** [comment]
I haven't worked on a Linux machine in a few years so I'm a bit rusty. If
you want to pull in all the dependencies to build from source, you can
issue the following command on a Debian based distribution (like Ubuntu), for example for NumPy:

`sudo apt-get build-dep python-numpy`

For Pysparse:

`sudo apt-get install atlas3-base-dev`

However, make sure to read the install files that come with Pysparse. It
may have changed since I last built Pysparse from source, but I had to edit the setup.py file that comes with Pysparse:

```
# default settings
library_dirs_list = ['/usr/lib/atlas']
```

Finally, issue the following commands:

```
python setup.py build
sudo python setup.py install
```

**Comment by MsURGZI** [comment]
> `sudo apt-get build-dep python-numpy`

returns `E: Unable to find a source package for python-numpy`. 
However, `apt install python-numpy` returns `python-numpy is already the newest version (1:1.11.0-1ubuntu1).`

> `sudo apt-get install atlas3-base-dev`
> returns 
> It looks like the package didn't exist anymore, and `apt-cache search` ([from here](https://superuser.com/questions/34894/fix-ubuntu-error-e-couldnt-find-package-package-name)) is not efficient to find it.
> However, I did [find](http://packages.ubuntu.com/trusty/libatlas-base-dev) two whose names are close: `libatlas3-base` and `libatlas-dev`.

After that, `sudo pip install pyparse` returns `Requirement already satisfied (use --upgrade to upgrade): pysparse in /usr/lib/python2.7/dist-packages`, so I assume it's been correctly installed.

When I run the example, it worked fine... until it told me `ImportError: No module named _tkinter, please install the python-tk package`

Then I run a `sudo apt-get install python-tk`. It told me `ImportError: No module named pyvtk`
Then I run a `sudo apt-get install pyvtk`, which didn't work, so I run a `sudo pip install pyvtk`, which was perfect.

I then re-launch my optimization, and it worked perfectly ! Thanks a lot ! :)

Got this, with an amazing bunch of 94 png files, for each step of the iteration.

```
===============================================================================
ToPy problem definition (TPD) file successfully parsed.
TPD file name: beam_2d_reci.tpd (v2007)
-------------------------------------------------------------------------------
Domain discretisation (NUM_ELEM_X x NUM_ELEM_Y) = 60 x 20
Element type (ELEM_K) = Q4
Filter radius (FILT_RAD) = 1.5
Number of iterations (NUM_ITER) = 94
Problem type (PROB_TYPE) = comp
Problem name (PROB_NAME) = beam_2d_reci
Continuation of penalisation factor (P_FAC) not specified
GSF not active
Damping factor (ETA) = 0.50
No passive elements (PASV_ELEM) specified
No active elements (ACTV_ELEM) specified
===============================================================================
 Iter | Obj. func.   | Vol.  | Change     | P_FAC | Q_FAC | Ave ETA | S-V frac. 
-------------------------------------------------------------------------------
   1  | 1.007023e+03 | 0.500 | 2.0000e-01 | 3.000 | 1.000 |  0.500  |  0.000 
   2  | 5.819346e+02 | 0.500 | 2.0000e-01 | 3.000 | 1.000 |  0.500  |  0.000 
   3  | 4.145937e+02 | 0.500 | 2.0000e-01 | 3.000 | 1.000 |  0.500  |  0.115 
   4  | 3.457323e+02 | 0.500 | 2.0000e-01 | 3.000 | 1.000 |  0.500  |  0.153 
   5  | 3.232380e+02 | 0.500 | 1.9465e-01 | 3.000 | 1.000 |  0.500  |  0.175 
   6  | 3.090768e+02 | 0.500 | 2.0000e-01 | 3.000 | 1.000 |  0.500  |  0.193 
   7  | 2.986085e+02 | 0.500 | 1.7186e-01 | 3.000 | 1.000 |  0.500  |  0.212 
   8  | 2.886144e+02 | 0.500 | 1.9676e-01 | 3.000 | 1.000 |  0.500  |  0.239 
   9  | 2.798081e+02 | 0.500 | 1.3974e-01 | 3.000 | 1.000 |  0.500  |  0.258 
  10  | 2.714769e+02 | 0.500 | 1.3511e-01 | 3.000 | 1.000 |  0.500  |  0.296 
  11  | 2.635672e+02 | 0.500 | 1.7834e-01 | 3.000 | 1.000 |  0.500  |  0.312 
  12  | 2.544862e+02 | 0.500 | 1.8537e-01 | 3.000 | 1.000 |  0.500  |  0.330 
  13  | 2.446055e+02 | 0.500 | 1.6560e-01 | 3.000 | 1.000 |  0.500  |  0.360 
  14  | 2.357136e+02 | 0.500 | 2.0000e-01 | 3.000 | 1.000 |  0.500  |  0.390 
  15  | 2.290298e+02 | 0.500 | 1.7826e-01 | 3.000 | 1.000 |  0.500  |  0.417 
  16  | 2.241446e+02 | 0.500 | 1.9421e-01 | 3.000 | 1.000 |  0.500  |  0.440 
  17  | 2.202598e+02 | 0.500 | 1.4401e-01 | 3.000 | 1.000 |  0.500  |  0.474 
  18  | 2.168037e+02 | 0.500 | 1.5751e-01 | 3.000 | 1.000 |  0.500  |  0.502 
  19  | 2.136238e+02 | 0.500 | 1.1801e-01 | 3.000 | 1.000 |  0.500  |  0.524 
  20  | 2.107824e+02 | 0.500 | 1.0455e-01 | 3.000 | 1.000 |  0.500  |  0.545 
  21  | 2.089882e+02 | 0.500 | 9.0088e-02 | 3.000 | 1.000 |  0.500  |  0.574 
  22  | 2.079761e+02 | 0.500 | 9.6715e-02 | 3.000 | 1.000 |  0.500  |  0.598 
  23  | 2.071975e+02 | 0.500 | 1.0533e-01 | 3.000 | 1.000 |  0.500  |  0.614 
  24  | 2.064571e+02 | 0.500 | 1.0864e-01 | 3.000 | 1.000 |  0.500  |  0.616 
  25  | 2.058439e+02 | 0.500 | 8.3551e-02 | 3.000 | 1.000 |  0.500  |  0.613 
  26  | 2.054229e+02 | 0.500 | 4.2878e-02 | 3.000 | 1.000 |  0.500  |  0.613 
  27  | 2.052594e+02 | 0.500 | 4.0862e-02 | 3.000 | 1.000 |  0.500  |  0.613 
  28  | 2.051785e+02 | 0.500 | 3.8877e-02 | 3.000 | 1.000 |  0.500  |  0.611 
  29  | 2.051004e+02 | 0.500 | 3.8358e-02 | 3.000 | 1.000 |  0.500  |  0.613 
  30  | 2.050198e+02 | 0.500 | 3.8989e-02 | 3.000 | 1.000 |  0.500  |  0.608 
  31  | 2.049356e+02 | 0.500 | 4.0356e-02 | 3.000 | 1.000 |  0.500  |  0.605 
  32  | 2.048469e+02 | 0.500 | 4.2787e-02 | 3.000 | 1.000 |  0.500  |  0.606 
  33  | 2.047494e+02 | 0.500 | 4.6481e-02 | 3.000 | 1.000 |  0.500  |  0.608 
  34  | 2.046364e+02 | 0.500 | 4.7377e-02 | 3.000 | 1.000 |  0.500  |  0.609 
  35  | 2.045347e+02 | 0.500 | 4.3237e-02 | 3.000 | 1.000 |  0.500  |  0.614 
  36  | 2.044744e+02 | 0.500 | 3.7911e-02 | 3.000 | 1.000 |  0.500  |  0.618 
  37  | 2.044372e+02 | 0.500 | 3.6668e-02 | 3.000 | 1.000 |  0.500  |  0.621 
  38  | 2.044107e+02 | 0.500 | 3.4915e-02 | 3.000 | 1.000 |  0.500  |  0.623 
  39  | 2.043879e+02 | 0.500 | 3.2581e-02 | 3.000 | 1.000 |  0.500  |  0.623 
  40  | 2.043641e+02 | 0.500 | 3.0160e-02 | 3.000 | 1.000 |  0.500  |  0.623 
  41  | 2.043386e+02 | 0.500 | 2.7831e-02 | 3.000 | 1.000 |  0.500  |  0.623 
  42  | 2.043091e+02 | 0.500 | 2.5690e-02 | 3.000 | 1.000 |  0.500  |  0.623 
  43  | 2.042746e+02 | 0.500 | 2.3850e-02 | 3.000 | 1.000 |  0.500  |  0.626 
  44  | 2.042373e+02 | 0.500 | 2.3643e-02 | 3.000 | 1.000 |  0.500  |  0.627 
  45  | 2.041980e+02 | 0.500 | 2.2971e-02 | 3.000 | 1.000 |  0.500  |  0.627 
  46  | 2.041587e+02 | 0.500 | 2.2444e-02 | 3.000 | 1.000 |  0.500  |  0.627 
  47  | 2.041197e+02 | 0.500 | 2.2035e-02 | 3.000 | 1.000 |  0.500  |  0.628 
  48  | 2.040799e+02 | 0.500 | 2.1761e-02 | 3.000 | 1.000 |  0.500  |  0.627 
  49  | 2.040386e+02 | 0.500 | 2.1119e-02 | 3.000 | 1.000 |  0.500  |  0.628 
  50  | 2.039963e+02 | 0.500 | 2.0527e-02 | 3.000 | 1.000 |  0.500  |  0.630 
  51  | 2.039533e+02 | 0.500 | 1.9881e-02 | 3.000 | 1.000 |  0.500  |  0.630 
  52  | 2.039112e+02 | 0.500 | 1.9128e-02 | 3.000 | 1.000 |  0.500  |  0.628 
  53  | 2.038695e+02 | 0.500 | 1.8262e-02 | 3.000 | 1.000 |  0.500  |  0.630 
  54  | 2.038286e+02 | 0.500 | 1.7278e-02 | 3.000 | 1.000 |  0.500  |  0.633 
  55  | 2.037902e+02 | 0.500 | 1.6067e-02 | 3.000 | 1.000 |  0.500  |  0.632 
  56  | 2.037569e+02 | 0.500 | 1.4565e-02 | 3.000 | 1.000 |  0.500  |  0.632 
  57  | 2.037290e+02 | 0.500 | 1.3429e-02 | 3.000 | 1.000 |  0.500  |  0.632 
  58  | 2.037056e+02 | 0.500 | 1.2177e-02 | 3.000 | 1.000 |  0.500  |  0.630 
  59  | 2.036848e+02 | 0.500 | 1.1735e-02 | 3.000 | 1.000 |  0.500  |  0.628 
  60  | 2.036670e+02 | 0.500 | 1.1236e-02 | 3.000 | 1.000 |  0.500  |  0.630 
  61  | 2.036503e+02 | 0.500 | 1.0754e-02 | 3.000 | 1.000 |  0.500  |  0.629 
  62  | 2.036343e+02 | 0.500 | 1.1656e-02 | 3.000 | 1.000 |  0.500  |  0.630 
  63  | 2.036172e+02 | 0.500 | 1.2563e-02 | 3.000 | 1.000 |  0.500  |  0.629 
  64  | 2.035973e+02 | 0.500 | 1.3617e-02 | 3.000 | 1.000 |  0.500  |  0.628 
  65  | 2.035767e+02 | 0.500 | 1.5218e-02 | 3.000 | 1.000 |  0.500  |  0.630 
  66  | 2.035540e+02 | 0.500 | 1.6888e-02 | 3.000 | 1.000 |  0.500  |  0.630 
  67  | 2.035317e+02 | 0.500 | 1.8091e-02 | 3.000 | 1.000 |  0.500  |  0.631 
  68  | 2.035133e+02 | 0.500 | 2.1145e-02 | 3.000 | 1.000 |  0.500  |  0.632 
  69  | 2.034971e+02 | 0.500 | 2.2620e-02 | 3.000 | 1.000 |  0.500  |  0.633 
  70  | 2.034862e+02 | 0.500 | 2.2770e-02 | 3.000 | 1.000 |  0.500  |  0.636 
  71  | 2.034769e+02 | 0.500 | 2.2506e-02 | 3.000 | 1.000 |  0.500  |  0.637 
  72  | 2.034690e+02 | 0.500 | 2.1380e-02 | 3.000 | 1.000 |  0.500  |  0.637 
  73  | 2.034593e+02 | 0.500 | 2.0314e-02 | 3.000 | 1.000 |  0.500  |  0.637 
  74  | 2.034518e+02 | 0.500 | 1.9259e-02 | 3.000 | 1.000 |  0.500  |  0.640 
  75  | 2.034467e+02 | 0.500 | 1.8380e-02 | 3.000 | 1.000 |  0.500  |  0.637 
  76  | 2.034408e+02 | 0.500 | 1.7696e-02 | 3.000 | 1.000 |  0.500  |  0.638 
  77  | 2.034340e+02 | 0.500 | 1.7564e-02 | 3.000 | 1.000 |  0.500  |  0.637 
  78  | 2.034298e+02 | 0.500 | 1.7379e-02 | 3.000 | 1.000 |  0.500  |  0.638 
  79  | 2.034247e+02 | 0.500 | 1.7119e-02 | 3.000 | 1.000 |  0.500  |  0.639 
  80  | 2.034170e+02 | 0.500 | 1.6789e-02 | 3.000 | 1.000 |  0.500  |  0.638 
  81  | 2.034073e+02 | 0.500 | 1.6468e-02 | 3.000 | 1.000 |  0.500  |  0.638 
  82  | 2.033956e+02 | 0.500 | 1.6037e-02 | 3.000 | 1.000 |  0.500  |  0.638 
  83  | 2.033852e+02 | 0.500 | 1.5412e-02 | 3.000 | 1.000 |  0.500  |  0.640 
  84  | 2.033758e+02 | 0.500 | 1.4691e-02 | 3.000 | 1.000 |  0.500  |  0.640 
  85  | 2.033658e+02 | 0.500 | 1.3825e-02 | 3.000 | 1.000 |  0.500  |  0.640 
  86  | 2.033548e+02 | 0.500 | 1.3143e-02 | 3.000 | 1.000 |  0.500  |  0.641 
  87  | 2.033434e+02 | 0.500 | 1.2582e-02 | 3.000 | 1.000 |  0.500  |  0.641 
  88  | 2.033314e+02 | 0.500 | 1.2052e-02 | 3.000 | 1.000 |  0.500  |  0.641 
  89  | 2.033184e+02 | 0.500 | 1.1529e-02 | 3.000 | 1.000 |  0.500  |  0.640 
  90  | 2.033044e+02 | 0.500 | 1.1004e-02 | 3.000 | 1.000 |  0.500  |  0.642 
  91  | 2.032898e+02 | 0.500 | 1.0467e-02 | 3.000 | 1.000 |  0.500  |  0.642 
  92  | 2.032754e+02 | 0.500 | 9.9121e-03 | 3.000 | 1.000 |  0.500  |  0.640 
  93  | 2.032621e+02 | 0.500 | 9.1201e-03 | 3.000 | 1.000 |  0.500  |  0.640 
  94  | 2.032493e+02 | 0.500 | 8.7215e-03 | 3.000 | 1.000 |  0.500  |  0.641 

Solid plus void to total elements fraction = 0.64083
94 iterations took 0.734 minutes (0.469 seconds/iteration)
Average of all ETA's = 0.500 (average of all a's = 1.000)
```

I even did a gif, [here](http://imgur.com/a/4GV8t). Thanks again !

**Comment by MsURGZI** [comment]
I would suggest to run

```
sudo apt-get install -y git python-dev python-tk python-pip libpython-dev libevent-dev libsuperlu-dev libblas-dev liblapack-dev libatlas3-base libatlas-dev

git clone https://github.com/williamhunter/topy

pip install --upgrade pip
sudo pip install matplotlib setuptools SymPy pysparse pyvtk
```

for anyone having troubles to install ToPy dependencies on a debian machine (ubuntu 16.04 tested, mint xfce18 tested).
